using System;
using System.Collections.Generic;
using System.Linq;

namespace ERP.Security
{
    /// <summary>
    /// مصدر واحد لصلاحيات النظام: كل صلاحية = كونترولر.أكشن (مثل SalesInvoices.Index).
    /// تُستخرج من الكونترولرات ويُستخدم نفس الكود في [RequirePermission] وفي المزامنة مع قاعدة البيانات.
    /// </summary>
    public static class PermissionCodes
    {
        /// <summary>
        /// تعريف الصلاحيات: (اسم الكونترولر بدون Controller، مصفوفة الأكشنات، الموديول بالعربي).
        /// كل أكشن يُنتج كود صلاحية = ControllerName.ActionName
        /// حذف من القائمة vs من داخل الشاشة: DeleteOneFromList و DeleteOneFromShow لكل من فواتير المبيعات والمشتريات.
        /// </summary>
        private static readonly (string Controller, string[] Actions, string Module)[] Definitions =
        {
            ("Global", new[] { "Open", "Edit", "Delete", "Export", "Print", "GeneralList", "ShowSummaries" }, "صلاحيات عامة"),
            ("Dashboard", new[] { "Sales" }, "لوحات التحكم"),
            ("Home", new[] { "Index" }, "لوحات التحكم"),
            ("SalesInvoices", new[] { "Index", "Show", "Create", "Edit", "Export", "SaveHeader", "GetProductsForDatalist", "GetAlternativeProducts", "GetSalesProductInfo", "DiagnosePolicy", "AddLineJson", "RemoveLineJson", "ClearAllLinesJson", "SaveTaxJson", "PostInvoice", "CreateFullReturn", "OpenInvoice", "Delete", "DeleteConfirmed", "DeleteOneFromList", "DeleteOneFromShow", "BulkDelete", "DeleteAll" }, "المبيعات"),
            ("SalesReturns", new[] { "Index", "Show", "Create", "Edit", "Delete", "Export", "SaveHeader", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetInvoiceItems", "SearchProductsForReturn", "GetProductsForReturnDatalist", "AddLineJson", "RemoveLineJson", "ClearLinesJson", "OpenReturn", "PostReturn" }, "المبيعات"),
            ("SalesOrders", new[] { "Index", "Show", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المبيعات"),
            ("SalesInvoiceLines", new[] { "Index", "Details", "Delete", "BulkDelete", "DeleteAll", "Export" }, "المبيعات"),
            ("SalesReturnLines", new[] { "Index", "Delete", "BulkDelete", "DeleteAll", "Export" }, "المبيعات"),
            ("SOLines", new[] { "Index", "Details", "Delete", "BulkDelete", "DeleteAll", "Export" }, "المبيعات"),
            ("ProductDiscountOverrides", new[] { "Index", "Edit", "Delete", "DeleteConfirmed", "Update" }, "المبيعات"),
            ("Customers", new[] { "Index", "Show", "Create", "Edit", "Delete", "Export", "GetDefaultAccountForParty", "GetDistrictsByGovernorate", "GetAreasByDistrict", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "العملاء"),
            ("CustomerLedger", new[] { "Index" }, "العملاء"),
            ("Products", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "Show", "Import", "GetColumnValues", "DeleteConfirmed", "BulkDelete", "DeleteAll", "SearchProducts", "SearchProductsByCode", "SearchParties" }, "إدارة المخازن"),
            ("Categories", new[] { "Index", "Show", "Details", "Create", "Edit", "Delete", "DeleteConfirmed", "BulkDelete", "DeleteAll", "Export" }, "إدارة المخازن"),
            ("Warehouses", new[] { "Index", "Show", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetColumnValues" }, "إدارة المخازن"),
            ("StockAdjustments", new[] { "Index", "Show", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll", "CreateHeaderJson", "UpdateHeaderJson", "GetStockAdjustmentProductInfo", "AddLineJson", "DeleteLineJson", "ClearLinesJson", "PostAdjustment", "OpenAdjustment" }, "إدارة المخازن"),
            ("StockTransfers", new[] { "Index", "Show", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll", "CreateHeaderJson", "UpdateHeaderJson", "GetTransferProductInfo", "AddLineJson", "DeleteLineJson", "ClearLinesJson", "PostTransfer", "OpenTransfer" }, "إدارة المخازن"),
            ("StockAdjustmentLines", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "إدارة المخازن"),
            ("StockTransferLines", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "إدارة المخازن"),
            ("StockLedger", new[] { "Index", "Export" }, "إدارة المخازن"),
            ("StockFifoMap", new[] { "Index", "Export" }, "إدارة المخازن"),
            ("StockBatches", new[] { "Index", "BulkDelete", "DeleteAll", "Export" }, "إدارة المخازن"),
            ("Batches", new[] { "Index", "Create", "Edit", "Show", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "إدارة المخازن"),
            ("ProductPriceHistory", new[] { "Index", "Export", "BulkDelete", "DeleteAll" }, "إدارة المخازن"),
            ("PurchaseInvoices", new[] { "Index", "Show", "Create", "Edit", "Delete", "Export", "SaveHeader", "AddLineJson", "RemoveLineJson", "ClearAllLinesJson", "SaveTaxJson", "PostInvoice", "CreateFullReturn", "OpenInvoice", "GetAlternativeProducts", "DeleteConfirmed", "DeleteOneFromList", "DeleteOneFromShow", "BulkDelete", "DeleteAll" }, "المشتريات"),
            ("PurchaseRequests", new[] { "Index", "Show", "Create", "Edit", "Delete", "Export", "SaveHeader", "AddLineJson", "RemoveLineJson", "ClearAllLinesJson", "SaveTaxJson", "GetAlternativeProducts", "GetProductDemandInfo", "GetProductSalesInPeriod", "DeleteConfirmed", "BulkDelete", "DeleteAll", "RecalcTotals", "ConvertToPurchaseInvoice", "RecalcAllTotals" }, "المشتريات"),
            ("PurchaseReturns", new[] { "Index", "Create", "Edit", "Delete", "Export", "SaveHeader", "BulkDelete", "DeleteAll", "GetInvoiceItems", "AddLineJson", "RemoveLineJson", "ClearLinesJson", "OpenReturn", "PostReturn" }, "المشتريات"),
            ("PILines", new[] { "Index", "BulkDelete", "DeleteAll", "Export" }, "المشتريات"),
            ("PRLines", new[] { "Index", "Show", "Create", "Edit", "Delete", "Export", "AddLineJson", "BulkDelete" }, "المشتريات"),
            ("PurchaseReturnLines", new[] { "Index", "Show", "Delete", "Export", "BulkDelete", "DeleteAll" }, "المشتريات"),
            ("Accounts", new[] { "Index", "Create", "Edit", "Delete", "Export", "BulkDelete", "DeleteAll" }, "الحسابات"),
            ("LedgerEntries", new[] { "Index", "Show", "Export", "BulkDelete", "DeleteAll" }, "الحسابات"),
            ("CashReceipts", new[] { "Index", "Show", "Details", "Create", "Edit", "Delete", "Export", "Open", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetCustomerAccount" }, "الحسابات"),
            ("CashPayments", new[] { "Index", "Show", "Details", "Create", "Edit", "Delete", "Export", "Open", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetCustomerAccount" }, "الحسابات"),
            ("DebitNotes", new[] { "Index", "Show", "Details", "Create", "Edit", "Delete", "Export", "Unlock", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetCustomerAccount" }, "الحسابات"),
            ("CreditNotes", new[] { "Index", "Show", "Details", "Create", "Edit", "Delete", "Export", "Unlock", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetCustomerAccount" }, "الحسابات"),
            ("Treasury", new[] { "Index", "ZeroTreasuryBalance" }, "الحسابات"),
            ("Reports", new[] { "ProductBalances", "ProductDetailsReport", "BonusReport", "CustomerBalances", "ExportCustomerBalances", "ExportProductBalances", "ProductProfits", "CustomerProfits", "SalesPerformanceReport", "PurchasePerformanceReport", "RouteReport", "FixOrphanedPaymentEntries", "ZeroCustomerBalance", "SyncStockBatchesFromLedger", "ZeroPhantomSalesReturnRemaining", "CleanOrphanedStockLedger", "ZeroProductBalance", "SaveManualDiscount" }, "التقارير"),
            ("ProductClassifications", new[] { "Index", "Create", "Edit", "Delete", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetColumnValues" }, "خط السير"),
            ("Routes", new[] { "Index", "Create", "Edit", "Delete", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetColumnValues" }, "خط السير"),
            ("SalesInvoiceRoutes", new[] { "Index", "Edit", "Entry", "GetInvoiceInfo", "GetEmployeesByJob", "GetFridgeProducts", "SaveRouteEntry", "SaveRouteJson" }, "خط السير"),
            ("Governorates", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المناطق الجغرافية"),
            ("Dstricts", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المناطق الجغرافية"),
            ("Areas", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المناطق الجغرافية"),
            ("Branches", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المناطق الجغرافية"),
            ("Cities", new[] { "Index", "Details", "Create", "Edit", "Delete", "DeleteConfirmed" }, "المناطق الجغرافية"),
            ("DocumentSeries", new[] { "Index", "Details", "Create", "Edit", "Delete", "DeleteConfirmed" }, "الإعدادات"),
            ("Settings", new[] { "ProductsExcelImport" }, "الإعدادات"),
            ("Policies", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "الإعدادات"),
            ("ProductGroups", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "الإعدادات"),
            ("ProductGroupPolicies", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "الإعدادات"),
            ("ProductBonusGroups", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "الإعدادات"),
            ("WarehousePolicyRules", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetPoliciesNotUsedForWarehouse" }, "الإعدادات"),
            ("UserActivityLogs", new[] { "Index", "Details", "Delete", "DeleteConfirmed", "BulkDelete", "DeleteAll", "Export" }, "الإعدادات"),
            ("Users", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المستخدمون والصلاحيات"),
            ("Roles", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المستخدمون والصلاحيات"),
            ("Permissions", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المستخدمون والصلاحيات"),
            ("RolePermissions", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetColumnValues" }, "المستخدمون والصلاحيات"),
            ("UserRoles", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll", "GetRolePermissionsPreview", "GetRolePermissionsEditable", "ResetToRoleDefaults" }, "المستخدمون والصلاحيات"),
            ("UserExtraPermissions", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المستخدمون والصلاحيات"),
            ("UserDeniedPermissions", new[] { "Index", "Details", "Create", "Edit", "Delete", "Export", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "المستخدمون والصلاحيات"),
            ("UserAccountVisibility", new[] { "Index", "Edit", "Update", "SeeAll" }, "المستخدمون والصلاحيات"),
            ("Departments", new[] { "Index", "Create", "Edit", "Delete", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "الموظفون"),
            ("Jobs", new[] { "Index", "Create", "Edit", "Delete", "DeleteConfirmed", "BulkDelete", "DeleteAll" }, "الموظفون"),
            ("Employees", new[] { "Index", "Create", "Edit", "Delete", "DeleteConfirmed", "Show", "Export", "BulkDelete", "DeleteAll" }, "الموظفون"),
        };

        /// <summary>
        /// أسماء الصلاحيات بالعربي المعبرة (للعرض في واجهة الصلاحيات والأدوار).
        /// إذا لم يُذكر الكود يُستخدم الافتراضي: الموديول + الكود.
        /// </summary>
        private static readonly Dictionary<string, string> NameArByCode = new(StringComparer.OrdinalIgnoreCase)
        {
            ["Global.Open"] = "عام — فتح مستند أو شاشة مغلقة",
            ["Global.Edit"] = "عام — التعديل والإنشاء والحفظ والترحيل",
            ["Global.Delete"] = "عام — حذف السجلات",
            ["Global.Export"] = "عام — التصدير",
            ["Global.Print"] = "عام — الطباعة",
            ["Global.GeneralList"] = "عام — قائمة عامة (عرض كل القوائم التشغيلية)",
            ["Global.ShowSummaries"] = "عام — إظهار إجماليات القوائم (كروت وسطر الجدول)",
            // لوحات التحكم — لوحة واحدة فقط: مبيعاتي الشخصية (تفتح مع الدخول للبرنامج)
            ["Dashboard.Sales"] = "مبيعاتي الشخصية",
            ["Home.Index"] = "الصفحة الرئيسية",
            // المبيعات — تسمية موحّدة: «قائمة فواتير…» = شاشة القائمة في الناف بار | «فاتورة مبيعات —» = شاشة الفاتورة | «قائمة أصناف المبيعات —» = قائمة أصناف المبيعات
            // قائمة فواتير المبيعات (قائمة الناف بار)
            ["SalesInvoices.Index"] = "قائمة فواتير المبيعات",
            ["SalesInvoices.Export"] = "قائمة فواتير المبيعات — تصدير",
            ["SalesInvoices.DeleteOneFromList"] = "قائمة فواتير المبيعات — حذف فاتورة من القائمة",
            ["SalesInvoices.BulkDelete"] = "قائمة فواتير المبيعات — حذف مجموعة فواتير من القائمة",
            ["SalesInvoices.DeleteAll"] = "قائمة فواتير المبيعات — حذف كل الفواتير من القائمة",
            // فاتورة المبيعات (شاشة إنشاء/عرض/تعديل الفاتورة)
            ["SalesInvoices.Show"] = "فاتورة مبيعات — عرض الشاشة",
            ["SalesInvoices.Create"] = "فاتورة مبيعات — إنشاء فاتورة جديدة",
            ["SalesInvoices.Edit"] = "فاتورة مبيعات — تعديل",
            ["SalesInvoices.Delete"] = "فاتورة مبيعات — طلب حذف (صفحة تأكيد)",
            ["SalesInvoices.DeleteConfirmed"] = "فاتورة مبيعات — تنفيذ الحذف",
            ["SalesInvoices.DeleteOneFromShow"] = "فاتورة مبيعات — حذف من داخل شاشة الفاتورة",
            ["SalesInvoices.PostInvoice"] = "فاتورة مبيعات — ترحيل",
            ["SalesInvoices.OpenInvoice"] = "فاتورة مبيعات — فتح للمراجعة والترحيل",
            ["SalesInvoices.CreateFullReturn"] = "فاتورة مبيعات — إنشاء مرتجع كامل من الفاتورة",
            ["SalesInvoices.SaveHeader"] = "فاتورة مبيعات — حفظ رأس الفاتورة (عميل، مخزن، إجماليات)",
            ["SalesInvoices.GetProductsForDatalist"] = "فاتورة مبيعات — اختيار صنف من قائمة البحث أثناء الإدخال",
            ["SalesInvoices.GetAlternativeProducts"] = "فاتورة مبيعات — عرض أصناف بديلة",
            ["SalesInvoices.GetSalesProductInfo"] = "فاتورة مبيعات — جلب معلومات الصنف عند إضافته",
            ["SalesInvoices.DiagnosePolicy"] = "فاتورة مبيعات — تشخيص سياسة العميل",
            ["SalesInvoices.AddLineJson"] = "فاتورة مبيعات — إضافة سطر صنف في جدول أصناف الفاتورة",
            ["SalesInvoices.RemoveLineJson"] = "فاتورة مبيعات — إزالة سطر صنف من جدول أصناف الفاتورة",
            ["SalesInvoices.ClearAllLinesJson"] = "فاتورة مبيعات — مسح كل سطور الأصناف في الفاتورة",
            ["SalesInvoices.SaveTaxJson"] = "فاتورة مبيعات — حفظ بيانات الضريبة من الشاشة",
            // الخصم اليدوي (قائمة منفصلة في المبيعات)
            ["ProductDiscountOverrides.Index"] = "قائمة الخصم اليدوي للبيع — عرض القائمة",
            ["ProductDiscountOverrides.Edit"] = "قائمة الخصم اليدوي للبيع — تعديل سجل",
            ["ProductDiscountOverrides.Delete"] = "قائمة الخصم اليدوي للبيع — حذف سجل",
            ["ProductDiscountOverrides.DeleteConfirmed"] = "قائمة الخصم اليدوي للبيع — تأكيد الحذف",
            ["ProductDiscountOverrides.Update"] = "قائمة الخصم اليدوي للبيع — حفظ التعديل من الجدول",
            // فواتير المشتريات
            ["PurchaseInvoices.Index"] = "قائمة فواتير المشتريات",
            ["PurchaseInvoices.Show"] = "عرض فاتورة مشتريات",
            ["PurchaseInvoices.Create"] = "إنشاء فاتورة مشتريات",
            ["PurchaseInvoices.Edit"] = "تعديل فاتورة مشتريات",
            ["PurchaseInvoices.Delete"] = "حذف فاتورة مشتريات (صفحة التأكيد)",
            ["PurchaseInvoices.DeleteConfirmed"] = "تنفيذ حذف فاتورة مشتريات",
            ["PurchaseInvoices.DeleteOneFromList"] = "مسح فاتورة واحدة من قائمة المشتريات",
            ["PurchaseInvoices.DeleteOneFromShow"] = "مسح فاتورة من داخل شاشة الفاتورة",
            ["PurchaseInvoices.BulkDelete"] = "مسح مجموعة فواتير من قائمة المشتريات",
            ["PurchaseInvoices.DeleteAll"] = "مسح كل فواتير قائمة المشتريات",
            ["PurchaseInvoices.Export"] = "تصدير فواتير المشتريات",
            ["PurchaseInvoices.PostInvoice"] = "ترحيل فاتورة المشتريات",
            ["PurchaseInvoices.OpenInvoice"] = "فتح فاتورة المشتريات",
            ["PurchaseInvoices.CreateFullReturn"] = "إنشاء مرتجع كامل للمشتريات",
            ["PurchaseInvoices.SaveHeader"] = "حفظ هيدر فاتورة المشتريات",
            ["PurchaseInvoices.AddLineJson"] = "إضافة سطر مشتريات (JSON)",
            ["PurchaseInvoices.RemoveLineJson"] = "إزالة سطر مشتريات (JSON)",
            ["PurchaseInvoices.ClearAllLinesJson"] = "مسح كل سطور المشتريات (JSON)",
            ["PurchaseInvoices.SaveTaxJson"] = "حفظ الضريبة — مشتريات (JSON)",
            ["PurchaseInvoices.GetAlternativeProducts"] = "أصناف بديلة — مشتريات",
            // العملاء
            ["Customers.Index"] = "قائمة العملاء",
            ["Customers.Show"] = "عرض عميل",
            ["Customers.Create"] = "إنشاء عميل",
            ["Customers.Edit"] = "تعديل عميل",
            ["Customers.Delete"] = "حذف عميل",
            ["Customers.DeleteOneFromList"] = "مسح عميل من القائمة",
            ["Customers.BulkDelete"] = "مسح مجموعة عملاء من القائمة",
            ["Customers.DeleteAll"] = "مسح كل العملاء من القائمة",
            ["Customers.Export"] = "تصدير العملاء",
            ["Customers.GetDefaultAccountForParty"] = "الحساب الافتراضي للطرف",
            ["Customers.GetDistrictsByGovernorate"] = "الأحياء حسب المحافظة",
            ["Customers.GetAreasByDistrict"] = "المناطق حسب الحي",
            ["Customers.DeleteConfirmed"] = "تأكيد حذف عميل",
            // المخازن والمنتجات
            ["Products.Index"] = "قائمة المنتجات",
            ["Products.Create"] = "إنشاء منتج",
            ["Products.Edit"] = "تعديل منتج",
            ["Products.Delete"] = "حذف منتج",
            ["Products.BulkDelete"] = "مسح مجموعة منتجات من القائمة",
            ["Products.DeleteAll"] = "مسح كل المنتجات من القائمة",
            ["Products.Export"] = "تصدير المنتجات",
            ["Products.Details"] = "تفاصيل منتج",
            ["Products.Show"] = "عرض منتج",
            ["Products.Import"] = "استيراد أرصدة أصناف وعملاء وخزينة (شاشة الاستيراد)",
            ["Settings.ProductsExcelImport"] = "استيراد أصناف من Excel (الإعدادات)",
            ["Products.GetColumnValues"] = "قيم عمود (فلتر)",
            ["Products.DeleteConfirmed"] = "تأكيد حذف منتج",
            ["Products.SearchProducts"] = "بحث أصناف",
            ["Products.SearchProductsByCode"] = "بحث أصناف بالكود",
            ["Products.SearchParties"] = "بحث أطراف",
            ["Categories.Index"] = "قائمة التصنيفات",
            ["Categories.BulkDelete"] = "مسح مجموعة تصنيفات من القائمة",
            ["Categories.DeleteAll"] = "مسح كل التصنيفات من القائمة",
            ["Categories.Show"] = "عرض تصنيف",
            ["Categories.Details"] = "تفاصيل تصنيف",
            ["Categories.Create"] = "إنشاء تصنيف",
            ["Categories.Edit"] = "تعديل تصنيف",
            ["Categories.Delete"] = "حذف تصنيف",
            ["Categories.DeleteConfirmed"] = "تأكيد حذف تصنيف",
            ["Categories.Export"] = "تصدير التصنيفات",
            ["Warehouses.Index"] = "قائمة المخازن",
            ["Warehouses.BulkDelete"] = "مسح مجموعة مخازن من القائمة",
            ["Warehouses.DeleteAll"] = "مسح كل المخازن من القائمة",
            ["Warehouses.Show"] = "عرض مخزن",
            ["Warehouses.Create"] = "إنشاء مخزن",
            ["Warehouses.Edit"] = "تعديل مخزن",
            ["Warehouses.Delete"] = "حذف مخزن",
            ["Warehouses.Export"] = "تصدير المخازن",
            ["Warehouses.DeleteConfirmed"] = "تأكيد حذف مخزن",
            ["Warehouses.GetColumnValues"] = "قيم عمود (فلتر)",
            // المستخدمون والصلاحيات
            ["Users.Index"] = "قائمة المستخدمين",
            ["Users.Create"] = "إنشاء مستخدم",
            ["Users.Edit"] = "تعديل مستخدم",
            ["Users.Delete"] = "حذف مستخدم",
            ["Users.BulkDelete"] = "مسح مجموعة مستخدمين من القائمة",
            ["Users.DeleteAll"] = "مسح كل المستخدمين من القائمة",
            ["Roles.Index"] = "قائمة الأدوار",
            ["Roles.BulkDelete"] = "مسح مجموعة أدوار من القائمة",
            ["Roles.DeleteAll"] = "مسح كل الأدوار من القائمة",
            ["Permissions.Index"] = "قائمة الصلاحيات",
            ["RolePermissions.Index"] = "ربط الصلاحيات بالأدوار",
            ["UserRoles.Index"] = "ربط المستخدمين بالأدوار",
            // قائمة أصناف أوامر البيع (ناف بار: قائمة أصناف أوامر المبيعات)
            ["SOLines.Index"] = "قائمة أصناف أوامر البيع — عرض القائمة",
            ["SOLines.Details"] = "قائمة أصناف أوامر البيع — تفاصيل سطر",
            ["SOLines.Delete"] = "قائمة أصناف أوامر البيع — حذف سطر",
            ["SOLines.BulkDelete"] = "قائمة أصناف أوامر البيع — حذف مجموعة",
            ["SOLines.DeleteAll"] = "قائمة أصناف أوامر البيع — حذف الكل",
            ["SOLines.Export"] = "قائمة أصناف أوامر البيع — تصدير",
            // قائمة أصناف المبيعات (ناف بار: قائمة أصناف المبيعات)
            ["SalesInvoiceLines.Index"] = "قائمة أصناف المبيعات — عرض القائمة",
            ["SalesInvoiceLines.Details"] = "قائمة أصناف المبيعات — تفاصيل سطر",
            ["SalesInvoiceLines.Delete"] = "قائمة أصناف المبيعات — حذف سطر",
            ["SalesInvoiceLines.BulkDelete"] = "قائمة أصناف المبيعات — حذف مجموعة",
            ["SalesInvoiceLines.DeleteAll"] = "قائمة أصناف المبيعات — حذف الكل",
            ["SalesInvoiceLines.Export"] = "قائمة أصناف المبيعات — تصدير",
            // قائمة مرتجعات المبيعات + شاشة المرتجع
            ["SalesReturns.Index"] = "قائمة مرتجعات المبيعات — عرض القائمة",
            ["SalesReturns.Export"] = "قائمة مرتجعات المبيعات — تصدير",
            ["SalesReturns.BulkDelete"] = "قائمة مرتجعات المبيعات — حذف مجموعة من القائمة",
            ["SalesReturns.DeleteAll"] = "قائمة مرتجعات المبيعات — حذف كل المرتجعات من القائمة",
            ["SalesReturns.Show"] = "مرتجع مبيعات — عرض الشاشة",
            ["SalesReturns.Create"] = "مرتجع مبيعات — إنشاء",
            ["SalesReturns.Edit"] = "مرتجع مبيعات — تعديل",
            ["SalesReturns.Delete"] = "مرتجع مبيعات — طلب حذف",
            ["SalesReturns.DeleteConfirmed"] = "مرتجع مبيعات — تأكيد الحذف",
            ["SalesReturns.SaveHeader"] = "مرتجع مبيعات — حفظ رأس المرتجع",
            ["SalesReturns.PostReturn"] = "مرتجع مبيعات — ترحيل",
            ["SalesReturns.OpenReturn"] = "مرتجع مبيعات — فتح للمراجعة",
            ["SalesReturns.GetInvoiceItems"] = "مرتجع مبيعات — جلب بنود الفاتورة الأصلية",
            ["SalesReturns.SearchProductsForReturn"] = "مرتجع مبيعات — بحث أصناف (مرتجع بدون فاتورة)",
            ["SalesReturns.GetProductsForReturnDatalist"] = "مرتجع مبيعات — قائمة أصناف (مرتجع بدون فاتورة)",
            ["SalesReturns.AddLineJson"] = "مرتجع مبيعات — إضافة سطر صنف في جدول أصناف المرتجع",
            ["SalesReturns.RemoveLineJson"] = "مرتجع مبيعات — إزالة سطر صنف من جدول أصناف المرتجع",
            ["SalesReturns.ClearLinesJson"] = "مرتجع مبيعات — مسح سطور الأصناف في المرتجع",
            // أوامر البيع — قائمة + شاشة أمر البيع
            ["SalesOrders.Index"] = "قائمة أوامر البيع — عرض القائمة",
            ["SalesOrders.Export"] = "قائمة أوامر البيع — تصدير",
            ["SalesOrders.BulkDelete"] = "قائمة أوامر البيع — حذف مجموعة من القائمة",
            ["SalesOrders.DeleteAll"] = "قائمة أوامر البيع — حذف كل الأوامر من القائمة",
            ["SalesOrders.Show"] = "أمر بيع — عرض الشاشة",
            ["SalesOrders.Create"] = "أمر بيع — إنشاء",
            ["SalesOrders.Edit"] = "أمر بيع — تعديل",
            ["SalesOrders.Delete"] = "أمر بيع — طلب حذف",
            ["SalesOrders.DeleteConfirmed"] = "أمر بيع — تأكيد الحذف",
            // قائمة أصناف مرتجعات المبيعات
            ["SalesReturnLines.Index"] = "قائمة أصناف مرتجعات المبيعات — عرض القائمة",
            ["SalesReturnLines.Delete"] = "قائمة أصناف مرتجعات المبيعات — حذف سطر",
            ["SalesReturnLines.BulkDelete"] = "قائمة أصناف مرتجعات المبيعات — حذف مجموعة",
            ["SalesReturnLines.DeleteAll"] = "قائمة أصناف مرتجعات المبيعات — حذف الكل",
            ["SalesReturnLines.Export"] = "قائمة أصناف مرتجعات المبيعات — تصدير",
            // خط السير — تصنيفات الأصناف
            ["ProductClassifications.Index"] = "قائمة تصنيفات الأصناف",
            ["ProductClassifications.Create"] = "إضافة تصنيف صنف",
            ["ProductClassifications.Edit"] = "تعديل تصنيف صنف",
            ["ProductClassifications.Delete"] = "حذف تصنيف صنف",
            ["ProductClassifications.DeleteConfirmed"] = "تنفيذ حذف تصنيف",
            ["ProductClassifications.BulkDelete"] = "مسح مجموعة تصنيفات",
            ["ProductClassifications.DeleteAll"] = "مسح كل التصنيفات",
            ["ProductClassifications.GetColumnValues"] = "قيم عمود (فلتر)",
            // خط السير — خطوط السير
            ["Routes.Index"] = "قائمة خطوط السير",
            ["Routes.Create"] = "إضافة خط سير",
            ["Routes.Edit"] = "تعديل خط سير",
            ["Routes.Delete"] = "حذف خط سير",
            ["Routes.DeleteConfirmed"] = "تنفيذ حذف خط سير",
            ["Routes.BulkDelete"] = "مسح مجموعة خطوط",
            ["Routes.DeleteAll"] = "مسح كل خطوط السير",
            ["Routes.GetColumnValues"] = "قيم عمود (فلتر)",
            // خط السير — بيانات خط السير للفواتير
            ["SalesInvoiceRoutes.Index"] = "قائمة بيانات خط السير للفواتير",
            ["SalesInvoiceRoutes.Edit"] = "تعديل بيانات خط السير لفاتورة",
            ["SalesInvoiceRoutes.Entry"] = "إدخال بيانات خط السير (شاشة التسلسل)",
            ["SalesInvoiceRoutes.GetInvoiceInfo"] = "جلب بيانات الفاتورة (API)",
            ["SalesInvoiceRoutes.GetEmployeesByJob"] = "جلب الموظفين حسب الوظيفة (API)",
            ["SalesInvoiceRoutes.GetFridgeProducts"] = "جلب أصناف الثلاجة (API)",
            ["SalesInvoiceRoutes.SaveRouteEntry"] = "تسجيل بيانات خط السير من شاشة الإدخال",
            ["SalesInvoiceRoutes.SaveRouteJson"] = "حفظ بيانات خط السير (API)",
            // الموظفون — أقسام
            ["Departments.Index"] = "قائمة الأقسام",
            ["Departments.Create"] = "إضافة قسم",
            ["Departments.Edit"] = "تعديل قسم",
            ["Departments.Delete"] = "حذف قسم",
            ["Departments.DeleteConfirmed"] = "تنفيذ حذف قسم",
            ["Departments.BulkDelete"] = "مسح مجموعة أقسام",
            ["Departments.DeleteAll"] = "مسح كل الأقسام",
            // الموظفون — وظائف
            ["Jobs.Index"] = "قائمة الوظائف",
            ["Jobs.Create"] = "إضافة وظيفة",
            ["Jobs.Edit"] = "تعديل وظيفة",
            ["Jobs.Delete"] = "حذف وظيفة",
            ["Jobs.DeleteConfirmed"] = "تنفيذ حذف وظيفة",
            ["Jobs.BulkDelete"] = "مسح مجموعة وظائف",
            ["Jobs.DeleteAll"] = "مسح كل الوظائف",
            // الموظفون — موظفين
            ["Employees.Index"] = "قائمة الموظفين",
            ["Employees.Create"] = "إضافة موظف",
            ["Employees.Edit"] = "تعديل موظف",
            ["Employees.Delete"] = "حذف موظف",
            ["Employees.DeleteConfirmed"] = "تنفيذ حذف موظف",
            ["Employees.Show"] = "عرض تفاصيل موظف",
            ["Employees.Export"] = "تصدير الموظفين",
            ["Employees.BulkDelete"] = "مسح مجموعة موظفين",
            ["Employees.DeleteAll"] = "مسح كل الموظفين",

            // دفتر العملاء
            ["CustomerLedger.Index"] = "دفتر عميل",
            // المخازن — مخزون وجرد وتحويل
            ["StockAdjustments.Index"] = "قائمة تسويات المخزون",
            ["StockAdjustments.Show"] = "عرض تسوية مخزون",
            ["StockAdjustments.Details"] = "تفاصيل تسوية مخزون",
            ["StockAdjustments.Create"] = "إنشاء تسوية مخزون",
            ["StockAdjustments.Edit"] = "تعديل تسوية مخزون",
            ["StockAdjustments.Delete"] = "حذف تسوية مخزون",
            ["StockAdjustments.Export"] = "تصدير تسويات المخزون",
            ["StockAdjustments.DeleteConfirmed"] = "تأكيد حذف تسوية",
            ["StockAdjustments.BulkDelete"] = "مسح مجموعة تسويات",
            ["StockAdjustments.DeleteAll"] = "مسح كل تسويات المخزون",
            ["StockAdjustments.CreateHeaderJson"] = "إنشاء هيدر تسوية (JSON)",
            ["StockAdjustments.UpdateHeaderJson"] = "تحديث هيدر تسوية (JSON)",
            ["StockAdjustments.GetStockAdjustmentProductInfo"] = "معلومات صنف للتسوية",
            ["StockAdjustments.AddLineJson"] = "إضافة سطر تسوية (JSON)",
            ["StockAdjustments.DeleteLineJson"] = "حذف سطر تسوية (JSON)",
            ["StockAdjustments.ClearLinesJson"] = "مسح سطور التسوية (JSON)",
            ["StockAdjustments.PostAdjustment"] = "ترحيل تسوية مخزون",
            ["StockAdjustments.OpenAdjustment"] = "فتح تسوية مخزون",
            ["StockTransfers.Index"] = "قائمة تحويلات المخزون",
            ["StockTransfers.Show"] = "عرض تحويل مخزون",
            ["StockTransfers.Details"] = "تفاصيل تحويل مخزون",
            ["StockTransfers.Create"] = "إنشاء تحويل مخزون",
            ["StockTransfers.Edit"] = "تعديل تحويل مخزون",
            ["StockTransfers.Delete"] = "حذف تحويل مخزون",
            ["StockTransfers.Export"] = "تصدير تحويلات المخزون",
            ["StockTransfers.DeleteConfirmed"] = "تأكيد حذف تحويل",
            ["StockTransfers.BulkDelete"] = "مسح مجموعة تحويلات",
            ["StockTransfers.DeleteAll"] = "مسح كل تحويلات المخزون",
            ["StockTransfers.CreateHeaderJson"] = "إنشاء هيدر تحويل (JSON)",
            ["StockTransfers.UpdateHeaderJson"] = "تحديث هيدر تحويل (JSON)",
            ["StockTransfers.GetTransferProductInfo"] = "معلومات صنف للتحويل",
            ["StockTransfers.AddLineJson"] = "إضافة سطر تحويل (JSON)",
            ["StockTransfers.DeleteLineJson"] = "حذف سطر تحويل (JSON)",
            ["StockTransfers.ClearLinesJson"] = "مسح سطور التحويل (JSON)",
            ["StockTransfers.PostTransfer"] = "ترحيل تحويل مخزون",
            ["StockTransfers.OpenTransfer"] = "فتح تحويل مخزون",
            ["StockAdjustmentLines.Index"] = "قائمة سطور تسويات المخزون",
            ["StockAdjustmentLines.Details"] = "تفاصيل سطر تسوية",
            ["StockAdjustmentLines.Create"] = "إنشاء سطر تسوية",
            ["StockAdjustmentLines.Edit"] = "تعديل سطر تسوية",
            ["StockAdjustmentLines.Delete"] = "حذف سطر تسوية",
            ["StockAdjustmentLines.Export"] = "تصدير سطور التسويات",
            ["StockAdjustmentLines.DeleteConfirmed"] = "تأكيد حذف سطر تسوية",
            ["StockAdjustmentLines.BulkDelete"] = "مسح مجموعة سطور تسوية",
            ["StockAdjustmentLines.DeleteAll"] = "مسح كل سطور التسويات",
            ["StockTransferLines.Index"] = "قائمة سطور تحويلات المخزون",
            ["StockTransferLines.Details"] = "تفاصيل سطر تحويل",
            ["StockTransferLines.Create"] = "إنشاء سطر تحويل",
            ["StockTransferLines.Edit"] = "تعديل سطر تحويل",
            ["StockTransferLines.Delete"] = "حذف سطر تحويل",
            ["StockTransferLines.Export"] = "تصدير سطور التحويلات",
            ["StockTransferLines.DeleteConfirmed"] = "تأكيد حذف سطر تحويل",
            ["StockTransferLines.BulkDelete"] = "مسح مجموعة سطور تحويل",
            ["StockTransferLines.DeleteAll"] = "مسح كل سطور التحويلات",
            ["StockLedger.Index"] = "دفتر حركة المخزون",
            ["StockLedger.Export"] = "تصدير دفتر حركة المخزون",
            ["StockFifoMap.Index"] = "خريطة FIFO للمخزون",
            ["StockFifoMap.Export"] = "تصدير خريطة FIFO",
            ["StockBatches.Index"] = "قائمة دفعات المخزون",
            ["StockBatches.BulkDelete"] = "مسح مجموعة دفعات",
            ["StockBatches.DeleteAll"] = "مسح كل الدفعات",
            ["StockBatches.Export"] = "تصدير دفعات المخزون",
            ["Batches.Index"] = "قائمة الدفعات",
            ["Batches.Create"] = "إنشاء دفعة",
            ["Batches.Edit"] = "تعديل دفعة",
            ["Batches.Show"] = "عرض دفعة",
            ["Batches.Delete"] = "حذف دفعة",
            ["Batches.Export"] = "تصدير الدفعات",
            ["Batches.DeleteConfirmed"] = "تأكيد حذف دفعة",
            ["Batches.BulkDelete"] = "مسح مجموعة دفعات",
            ["Batches.DeleteAll"] = "مسح كل الدفعات",
            ["ProductPriceHistory.Index"] = "سجل أسعار الأصناف",
            ["ProductPriceHistory.Export"] = "تصدير سجل الأسعار",
            ["ProductPriceHistory.BulkDelete"] = "مسح مجموعة سجلات أسعار",
            ["ProductPriceHistory.DeleteAll"] = "مسح كل سجل الأسعار",
            // المشتريات
            ["PurchaseRequests.Index"] = "قائمة طلبات الشراء",
            ["PurchaseRequests.Show"] = "عرض طلب شراء",
            ["PurchaseRequests.Create"] = "إنشاء طلب شراء",
            ["PurchaseRequests.Edit"] = "تعديل طلب شراء",
            ["PurchaseRequests.Delete"] = "حذف طلب شراء",
            ["PurchaseRequests.Export"] = "تصدير طلبات الشراء",
            ["PurchaseRequests.SaveHeader"] = "حفظ هيدر طلب الشراء",
            ["PurchaseRequests.AddLineJson"] = "إضافة سطر (JSON)",
            ["PurchaseRequests.RemoveLineJson"] = "إزالة سطر (JSON)",
            ["PurchaseRequests.ClearAllLinesJson"] = "مسح كل السطور (JSON)",
            ["PurchaseRequests.SaveTaxJson"] = "حفظ الضريبة (JSON)",
            ["PurchaseRequests.GetAlternativeProducts"] = "أصناف بديلة",
            ["PurchaseRequests.GetProductDemandInfo"] = "معلومات طلب الصنف",
            ["PurchaseRequests.GetProductSalesInPeriod"] = "مبيعات الصنف في فترة",
            ["PurchaseRequests.DeleteConfirmed"] = "تأكيد حذف طلب شراء",
            ["PurchaseRequests.BulkDelete"] = "مسح مجموعة طلبات شراء",
            ["PurchaseRequests.DeleteAll"] = "مسح كل طلبات الشراء",
            ["PurchaseRequests.RecalcTotals"] = "إعادة حساب الإجماليات",
            ["PurchaseRequests.ConvertToPurchaseInvoice"] = "تحويل إلى فاتورة مشتريات",
            ["PurchaseRequests.RecalcAllTotals"] = "إعادة حساب كل الإجماليات",
            ["PurchaseReturns.Index"] = "قائمة مرتجعات المشتريات",
            ["PurchaseReturns.Create"] = "إنشاء مرتجع مشتريات",
            ["PurchaseReturns.Edit"] = "تعديل مرتجع مشتريات",
            ["PurchaseReturns.Delete"] = "حذف مرتجع مشتريات",
            ["PurchaseReturns.Export"] = "تصدير مرتجعات المشتريات",
            ["PurchaseReturns.SaveHeader"] = "حفظ هيدر المرتجع",
            ["PurchaseReturns.BulkDelete"] = "مسح مجموعة مرتجعات",
            ["PurchaseReturns.DeleteAll"] = "مسح كل مرتجعات المشتريات",
            ["PurchaseReturns.GetInvoiceItems"] = "بنود الفاتورة للمرتجع",
            ["PurchaseReturns.AddLineJson"] = "إضافة سطر (JSON)",
            ["PurchaseReturns.RemoveLineJson"] = "إزالة سطر (JSON)",
            ["PurchaseReturns.ClearLinesJson"] = "مسح السطور (JSON)",
            ["PurchaseReturns.OpenReturn"] = "فتح مرتجع مشتريات",
            ["PurchaseReturns.PostReturn"] = "ترحيل مرتجع مشتريات",
            ["PILines.Index"] = "قائمة سطور فواتير المشتريات",
            ["PILines.BulkDelete"] = "مسح مجموعة سطور فواتير مشتريات",
            ["PILines.DeleteAll"] = "مسح كل سطور فواتير المشتريات",
            ["PILines.Export"] = "تصدير سطور فواتير المشتريات",
            ["PRLines.Index"] = "قائمة سطور مرتجعات المشتريات",
            ["PRLines.Show"] = "عرض سطر مرتجع مشتريات",
            ["PRLines.Create"] = "إنشاء سطر مرتجع",
            ["PRLines.Edit"] = "تعديل سطر مرتجع",
            ["PRLines.Delete"] = "حذف سطر مرتجع",
            ["PRLines.Export"] = "تصدير سطور المرتجعات",
            ["PRLines.AddLineJson"] = "إضافة سطر (JSON)",
            ["PRLines.BulkDelete"] = "مسح مجموعة سطور مرتجعات",
            ["PurchaseReturnLines.Index"] = "قائمة أصناف مرتجعات المشتريات",
            ["PurchaseReturnLines.Show"] = "عرض سطر مرتجع",
            ["PurchaseReturnLines.Delete"] = "حذف سطر مرتجع",
            ["PurchaseReturnLines.Export"] = "تصدير أصناف المرتجعات",
            ["PurchaseReturnLines.BulkDelete"] = "مسح مجموعة أصناف مرتجعات",
            ["PurchaseReturnLines.DeleteAll"] = "مسح كل أصناف المرتجعات",
            // الحسابات والخزينة
            ["Accounts.Index"] = "قائمة الحسابات",
            ["Accounts.Create"] = "إنشاء حساب",
            ["Accounts.Edit"] = "تعديل حساب",
            ["Accounts.Delete"] = "حذف حساب",
            ["Accounts.Export"] = "تصدير الحسابات",
            ["Accounts.BulkDelete"] = "مسح مجموعة حسابات",
            ["Accounts.DeleteAll"] = "مسح كل الحسابات",
            ["LedgerEntries.Index"] = "قائمة قيود اليومية",
            ["LedgerEntries.Show"] = "عرض قيد",
            ["LedgerEntries.Export"] = "تصدير القيود",
            ["LedgerEntries.BulkDelete"] = "مسح مجموعة قيود",
            ["LedgerEntries.DeleteAll"] = "مسح كل القيود",
            ["CashReceipts.Index"] = "قائمة إذون استلام نقدية",
            ["CashReceipts.Show"] = "عرض إذن استلام",
            ["CashReceipts.Details"] = "تفاصيل إذن استلام",
            ["CashReceipts.Create"] = "إنشاء إذن استلام",
            ["CashReceipts.Edit"] = "تعديل إذن استلام",
            ["CashReceipts.Delete"] = "حذف إذن استلام",
            ["CashReceipts.Export"] = "تصدير إذون الاستلام",
            ["CashReceipts.Open"] = "فتح إذن استلام",
            ["CashReceipts.DeleteConfirmed"] = "تأكيد حذف إذن استلام",
            ["CashReceipts.BulkDelete"] = "مسح مجموعة إذون",
            ["CashReceipts.DeleteAll"] = "مسح كل إذون الاستلام",
            ["CashReceipts.GetCustomerAccount"] = "حساب العميل للإذن",
            ["CashPayments.Index"] = "قائمة إذون صرف نقدية",
            ["CashPayments.Show"] = "عرض إذن صرف",
            ["CashPayments.Details"] = "تفاصيل إذن صرف",
            ["CashPayments.Create"] = "إنشاء إذن صرف",
            ["CashPayments.Edit"] = "تعديل إذن صرف",
            ["CashPayments.Delete"] = "حذف إذن صرف",
            ["CashPayments.Export"] = "تصدير إذون الصرف",
            ["CashPayments.Open"] = "فتح إذن صرف",
            ["CashPayments.DeleteConfirmed"] = "تأكيد حذف إذن صرف",
            ["CashPayments.BulkDelete"] = "مسح مجموعة إذون صرف",
            ["CashPayments.DeleteAll"] = "مسح كل إذون الصرف",
            ["CashPayments.GetCustomerAccount"] = "حساب الطرف للإذن",
            ["DebitNotes.Index"] = "قائمة إشعارات مدينة",
            ["DebitNotes.Show"] = "عرض إشعار مدين",
            ["DebitNotes.Details"] = "تفاصيل إشعار مدين",
            ["DebitNotes.Create"] = "إنشاء إشعار مدين",
            ["DebitNotes.Edit"] = "تعديل إشعار مدين",
            ["DebitNotes.Delete"] = "حذف إشعار مدين",
            ["DebitNotes.Export"] = "تصدير إشعارات مدينة",
            ["DebitNotes.Unlock"] = "إلغاء قفل إشعار مدين",
            ["DebitNotes.DeleteConfirmed"] = "تأكيد حذف إشعار مدين",
            ["DebitNotes.BulkDelete"] = "مسح مجموعة إشعارات",
            ["DebitNotes.DeleteAll"] = "مسح كل الإشعارات المدينة",
            ["DebitNotes.GetCustomerAccount"] = "حساب الطرف للإشعار",
            ["CreditNotes.Index"] = "قائمة إشعارات دائنة",
            ["CreditNotes.Show"] = "عرض إشعار دائن",
            ["CreditNotes.Details"] = "تفاصيل إشعار دائن",
            ["CreditNotes.Create"] = "إنشاء إشعار دائن",
            ["CreditNotes.Edit"] = "تعديل إشعار دائن",
            ["CreditNotes.Delete"] = "حذف إشعار دائن",
            ["CreditNotes.Export"] = "تصدير إشعارات دائنة",
            ["CreditNotes.Unlock"] = "إلغاء قفل إشعار دائن",
            ["CreditNotes.DeleteConfirmed"] = "تأكيد حذف إشعار دائن",
            ["CreditNotes.BulkDelete"] = "مسح مجموعة إشعارات",
            ["CreditNotes.DeleteAll"] = "مسح كل الإشعارات الدائنة",
            ["CreditNotes.GetCustomerAccount"] = "حساب الطرف للإشعار",
            ["Treasury.Index"] = "شاشة الخزينة",
            ["Treasury.ZeroTreasuryBalance"] = "تصفير رصيد خزينة",
            // التقارير والصيانة
            ["Reports.ProductBalances"] = "تقرير أرصدة المخزون",
            ["Reports.ProductDetailsReport"] = "تقرير تفاصيل أصناف",
            ["Reports.BonusReport"] = "تقرير البونص",
            ["Reports.CustomerBalances"] = "أرصدة العملاء",
            ["Reports.ExportCustomerBalances"] = "تصدير أرصدة العملاء",
            ["Reports.ExportProductBalances"] = "تصدير أرصدة المخزون",
            ["Reports.ProductProfits"] = "أرباح الأصناف",
            ["Reports.CustomerProfits"] = "أرباح العملاء",
            ["Reports.SalesPerformanceReport"] = "تقرير أداء المبيعات",
            ["Reports.PurchasePerformanceReport"] = "تقرير أداء المشتريات",
            ["Reports.RouteReport"] = "تقرير خط السير",
            ["Reports.FixOrphanedPaymentEntries"] = "إصلاح قيود دفع يتيمة",
            ["Reports.ZeroCustomerBalance"] = "تصفير رصيد عميل",
            ["Reports.SyncStockBatchesFromLedger"] = "مزامنة دفعات المخزون من الأستاذ",
            ["Reports.ZeroPhantomSalesReturnRemaining"] = "تصفير متبقي مرتجع مبيعات وهمي",
            ["Reports.CleanOrphanedStockLedger"] = "تنظيف دفتر مخزون يتيم",
            ["Reports.ZeroProductBalance"] = "تصفير رصيد صنف",
            ["Reports.SaveManualDiscount"] = "حفظ خصم يدوي",
            // المناطق الجغرافية
            ["Governorates.Index"] = "قائمة المحافظات",
            ["Governorates.Details"] = "تفاصيل محافظة",
            ["Governorates.Create"] = "إضافة محافظة",
            ["Governorates.Edit"] = "تعديل محافظة",
            ["Governorates.Delete"] = "حذف محافظة",
            ["Governorates.Export"] = "تصدير المحافظات",
            ["Governorates.DeleteConfirmed"] = "تأكيد حذف محافظة",
            ["Governorates.BulkDelete"] = "مسح مجموعة محافظات",
            ["Governorates.DeleteAll"] = "مسح كل المحافظات",
            ["Dstricts.Index"] = "قائمة المراكز والأحياء",
            ["Dstricts.Details"] = "تفاصيل حي/مركز",
            ["Dstricts.Create"] = "إضافة حي/مركز",
            ["Dstricts.Edit"] = "تعديل حي/مركز",
            ["Dstricts.Delete"] = "حذف حي/مركز",
            ["Dstricts.Export"] = "تصدير المراكز والأحياء",
            ["Dstricts.DeleteConfirmed"] = "تأكيد حذف",
            ["Dstricts.BulkDelete"] = "مسح مجموعة",
            ["Dstricts.DeleteAll"] = "مسح الكل",
            ["Areas.Index"] = "قائمة المناطق",
            ["Areas.Details"] = "تفاصيل منطقة",
            ["Areas.Create"] = "إضافة منطقة",
            ["Areas.Edit"] = "تعديل منطقة",
            ["Areas.Delete"] = "حذف منطقة",
            ["Areas.Export"] = "تصدير المناطق",
            ["Areas.DeleteConfirmed"] = "تأكيد حذف منطقة",
            ["Areas.BulkDelete"] = "مسح مجموعة مناطق",
            ["Areas.DeleteAll"] = "مسح كل المناطق",
            ["Branches.Index"] = "قائمة الفروع",
            ["Branches.Details"] = "تفاصيل فرع",
            ["Branches.Create"] = "إضافة فرع",
            ["Branches.Edit"] = "تعديل فرع",
            ["Branches.Delete"] = "حذف فرع",
            ["Branches.Export"] = "تصدير الفروع",
            ["Branches.DeleteConfirmed"] = "تأكيد حذف فرع",
            ["Branches.BulkDelete"] = "مسح مجموعة فروع",
            ["Branches.DeleteAll"] = "مسح كل الفروع",
            ["Cities.Index"] = "قائمة المدن",
            ["Cities.Details"] = "تفاصيل مدينة",
            ["Cities.Create"] = "إضافة مدينة",
            ["Cities.Edit"] = "تعديل مدينة",
            ["Cities.Delete"] = "حذف مدينة",
            ["Cities.DeleteConfirmed"] = "تأكيد حذف مدينة",
            // الإعدادات — سلاسل المستندات والسياسات
            ["DocumentSeries.Index"] = "قائمة سلاسل المستندات",
            ["DocumentSeries.Details"] = "تفاصيل سلسلة مستندات",
            ["DocumentSeries.Create"] = "إنشاء سلسلة مستندات",
            ["DocumentSeries.Edit"] = "تعديل سلسلة مستندات",
            ["DocumentSeries.Delete"] = "حذف سلسلة مستندات",
            ["DocumentSeries.DeleteConfirmed"] = "تأكيد حذف سلسلة",
            ["Policies.Index"] = "قائمة سياسات البيع",
            ["Policies.Details"] = "تفاصيل سياسة بيع",
            ["Policies.Create"] = "إنشاء سياسة بيع",
            ["Policies.Edit"] = "تعديل سياسة بيع",
            ["Policies.Delete"] = "حذف سياسة بيع",
            ["Policies.Export"] = "تصدير السياسات",
            ["Policies.DeleteConfirmed"] = "تأكيد حذف سياسة",
            ["Policies.BulkDelete"] = "مسح مجموعة سياسات",
            ["Policies.DeleteAll"] = "مسح كل السياسات",
            ["ProductGroups.Index"] = "قائمة مجموعات الأصناف",
            ["ProductGroups.Details"] = "تفاصيل مجموعة أصناف",
            ["ProductGroups.Create"] = "إنشاء مجموعة أصناف",
            ["ProductGroups.Edit"] = "تعديل مجموعة أصناف",
            ["ProductGroups.Delete"] = "حذف مجموعة أصناف",
            ["ProductGroups.Export"] = "تصدير المجموعات",
            ["ProductGroups.DeleteConfirmed"] = "تأكيد حذف مجموعة",
            ["ProductGroups.BulkDelete"] = "مسح مجموعة مجموعات",
            ["ProductGroups.DeleteAll"] = "مسح كل المجموعات",
            ["ProductGroupPolicies.Index"] = "قائمة ربط المجموعات بالسياسات",
            ["ProductGroupPolicies.Details"] = "تفاصيل ربط مجموعة بسياسة",
            ["ProductGroupPolicies.Create"] = "إنشاء ربط مجموعة بسياسة",
            ["ProductGroupPolicies.Edit"] = "تعديل ربط مجموعة بسياسة",
            ["ProductGroupPolicies.Delete"] = "حذف ربط مجموعة بسياسة",
            ["ProductGroupPolicies.Export"] = "تصدير الربط",
            ["ProductGroupPolicies.DeleteConfirmed"] = "تأكيد حذف الربط",
            ["ProductGroupPolicies.BulkDelete"] = "مسح مجموعة روابط",
            ["ProductGroupPolicies.DeleteAll"] = "مسح كل الروابط",
            ["ProductBonusGroups.Index"] = "قائمة مجموعات البونص",
            ["ProductBonusGroups.Details"] = "تفاصيل مجموعة بونص",
            ["ProductBonusGroups.Create"] = "إنشاء مجموعة بونص",
            ["ProductBonusGroups.Edit"] = "تعديل مجموعة بونص",
            ["ProductBonusGroups.Delete"] = "حذف مجموعة بونص",
            ["ProductBonusGroups.Export"] = "تصدير مجموعات البونص",
            ["ProductBonusGroups.DeleteConfirmed"] = "تأكيد حذف مجموعة بونص",
            ["ProductBonusGroups.BulkDelete"] = "مسح مجموعة مجموعات بونص",
            ["ProductBonusGroups.DeleteAll"] = "مسح كل مجموعات البونص",
            ["WarehousePolicyRules.Index"] = "قائمة قواعد سياسات المخازن",
            ["WarehousePolicyRules.Details"] = "تفاصيل قاعدة مخزن",
            ["WarehousePolicyRules.Create"] = "إنشاء قاعدة مخزن",
            ["WarehousePolicyRules.Edit"] = "تعديل قاعدة مخزن",
            ["WarehousePolicyRules.Delete"] = "حذف قاعدة مخزن",
            ["WarehousePolicyRules.Export"] = "تصدير القواعد",
            ["WarehousePolicyRules.DeleteConfirmed"] = "تأكيد حذف قاعدة",
            ["WarehousePolicyRules.BulkDelete"] = "مسح مجموعة قواعد",
            ["WarehousePolicyRules.DeleteAll"] = "مسح كل القواعد",
            ["WarehousePolicyRules.GetPoliciesNotUsedForWarehouse"] = "سياسات غير مستخدمة للمخزن",
            ["UserActivityLogs.Index"] = "سجل نشاط المستخدمين",
            ["UserActivityLogs.Details"] = "تفاصيل سجل نشاط",
            ["UserActivityLogs.Delete"] = "حذف سجل نشاط",
            ["UserActivityLogs.DeleteConfirmed"] = "تأكيد حذف سجل",
            ["UserActivityLogs.BulkDelete"] = "مسح مجموعة سجلات",
            ["UserActivityLogs.DeleteAll"] = "مسح كل السجلات",
            ["UserActivityLogs.Export"] = "تصدير سجل النشاط",
            // المستخدمون والصلاحيات — إكمال
            ["Users.Details"] = "تفاصيل مستخدم",
            ["Users.Export"] = "تصدير المستخدمين",
            ["Users.DeleteConfirmed"] = "تأكيد حذف مستخدم",
            ["Roles.Details"] = "تفاصيل دور",
            ["Roles.Create"] = "إنشاء دور",
            ["Roles.Edit"] = "تعديل دور",
            ["Roles.Delete"] = "حذف دور",
            ["Roles.Export"] = "تصدير الأدوار",
            ["Roles.DeleteConfirmed"] = "تأكيد حذف دور",
            ["Permissions.Details"] = "تفاصيل صلاحية",
            ["Permissions.Create"] = "إنشاء صلاحية",
            ["Permissions.Edit"] = "تعديل صلاحية",
            ["Permissions.Delete"] = "حذف صلاحية",
            ["Permissions.Export"] = "تصدير الصلاحيات",
            ["Permissions.DeleteConfirmed"] = "تأكيد حذف صلاحية",
            ["Permissions.BulkDelete"] = "مسح مجموعة صلاحيات",
            ["Permissions.DeleteAll"] = "مسح كل الصلاحيات",
            ["RolePermissions.Details"] = "تفاصيل ربط دور بصلاحية",
            ["RolePermissions.Create"] = "إنشاء ربط صلاحية بدور",
            ["RolePermissions.Edit"] = "تعديل ربط صلاحية بدور",
            ["RolePermissions.Delete"] = "حذف ربط صلاحية بدور",
            ["RolePermissions.Export"] = "تصدير الربط",
            ["RolePermissions.DeleteConfirmed"] = "تأكيد حذف الربط",
            ["RolePermissions.BulkDelete"] = "مسح مجموعة روابط",
            ["RolePermissions.DeleteAll"] = "مسح كل الروابط",
            ["RolePermissions.GetColumnValues"] = "قيم عمود (فلتر)",
            ["UserRoles.Details"] = "تفاصيل ربط مستخدم بدور",
            ["UserRoles.Create"] = "إنشاء ربط مستخدم بدور",
            ["UserRoles.Edit"] = "تعديل ربط مستخدم بدور",
            ["UserRoles.Delete"] = "حذف ربط مستخدم بدور",
            ["UserRoles.Export"] = "تصدير الربط",
            ["UserRoles.DeleteConfirmed"] = "تأكيد حذف الربط",
            ["UserRoles.BulkDelete"] = "مسح مجموعة روابط",
            ["UserRoles.DeleteAll"] = "مسح كل الروابط",
            ["UserRoles.GetRolePermissionsPreview"] = "معاينة صلاحيات الدور",
            ["UserRoles.GetRolePermissionsEditable"] = "صلاحيات الدور القابلة للتعديل",
            ["UserRoles.ResetToRoleDefaults"] = "ربط المستخدمين بالأدوار — إعادة ضبط صلاحيات المستخدم لتطابق الدور",
            ["UserExtraPermissions.Details"] = "تفاصيل صلاحية إضافية",
            ["UserExtraPermissions.Create"] = "إضافة صلاحية إضافية",
            ["UserExtraPermissions.Edit"] = "تعديل صلاحية إضافية",
            ["UserExtraPermissions.Delete"] = "حذف صلاحية إضافية",
            ["UserExtraPermissions.Export"] = "تصدير الصلاحيات الإضافية",
            ["UserExtraPermissions.DeleteConfirmed"] = "تأكيد الحذف",
            ["UserExtraPermissions.BulkDelete"] = "مسح مجموعة",
            ["UserExtraPermissions.DeleteAll"] = "مسح الكل",
            ["UserDeniedPermissions.Details"] = "تفاصيل صلاحية مرفوضة",
            ["UserDeniedPermissions.Create"] = "إضافة رفض صلاحية",
            ["UserDeniedPermissions.Edit"] = "تعديل رفض صلاحية",
            ["UserDeniedPermissions.Delete"] = "حذف رفض صلاحية",
            ["UserDeniedPermissions.Export"] = "تصدير الرفض",
            ["UserDeniedPermissions.DeleteConfirmed"] = "تأكيد الحذف",
            ["UserDeniedPermissions.BulkDelete"] = "مسح مجموعة",
            ["UserDeniedPermissions.DeleteAll"] = "مسح الكل",

            // الحسابات المسموح رؤيتها لكل مستخدم
            ["UserAccountVisibility.Index"] = "الحسابات المسموح رؤيتها (موجّه — استخدم صلاحيات الأدوار)",
            ["UserAccountVisibility.Edit"] = "تعديل ظهور الحسابات (موجّه — استخدم صلاحيات الأدوار)",
            ["UserAccountVisibility.Update"] = "حفظ ظهور الحسابات (موجّه — استخدم صلاحيات الأدوار)",
            ["UserAccountVisibility.SeeAll"] = "رؤية جميع الحسابات (بما فيها المستثمر)",
        };

        /// <summary>
        /// يُنشئ كود صلاحية من اسم الكونترولر والأكشن (للاستخدام في HasPermissionAsync فقط، وليس في السمات).
        /// في [RequirePermission] استخدم النص الحرفي: [RequirePermission("SalesInvoices.Index")]
        /// </summary>
        public static string Code(string controllerName, string actionName)
        {
            if (string.IsNullOrWhiteSpace(controllerName) || string.IsNullOrWhiteSpace(actionName))
                return "";
            return $"{controllerName.Trim()}.{actionName.Trim()}";
        }

        /// <summary>
        /// ترجع كل الصلاحيات للمزامنة مع قاعدة البيانات: مسح القديم وإعادة البناء من هذا المصدر فقط.
        /// Code = ControllerName.ActionName بالضبط كما في الكونترولرات.
        /// </summary>
        public static IEnumerable<(string Code, string NameAr, string Module)> GetAllForSync()
        {
            foreach (var (controller, actions, module) in Definitions)
            {
                foreach (var action in actions.Distinct(StringComparer.OrdinalIgnoreCase))
                {
                    var code = $"{controller}.{action}";
                    var nameAr = NameArByCode.TryGetValue(code, out var name) ? name : $"{module} - {code}";
                    yield return (code, nameAr, module);
                }
            }
        }
    }
}
